Workaround for weird error with Intel compiler on MacOS
- Intel compiler throws error:
  'too few arguments in invocation of macro "howmany"'

- minor changes to Makefile and profile.txx